api:
  endpoint: "http://worldtimeapi.org/api/timezone/"
  continent: "Europe"
server:
  port: 1313

spring:
  datasource:
    url: jdbc:mysql://localhost:3386/test
    username: root
    password: test


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
